//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogInLogOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorID { get; set; }
        public bool ActiveDonor { get; set; }
        public string DonorName { get; set; }
        public string BloodType { get; set; }
        public string RhFactor { get; set; }
        public System.DateTime DonorDateofBirth { get; set; }
        public string DonorPhoneNr { get; set; }
        public string DonorEmail { get; set; }
        public System.DateTime LastScreeningDate { get; set; }
        public string DonorIdentifier { get; set; }
    
        public virtual Donation Donation { get; set; }
    }
}
