//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogInLogOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageBloodDrive
    {
        public int bloodDrive_id { get; set; }
        public string drive_name { get; set; }
        public System.DateTime event_date { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public string registrationEmail { get; set; }
        public string registrationPhone { get; set; }
        public string venue_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> zip { get; set; }
    }
}
